
language: swift

before_install:
   - rvm use system
   - sudo gem install cocoapods -v '0.39.0'

script:
    xctool -workspace Big Neon.xcworkspace -scheme BigNeonStudioTests build -sdk iphonesimulator
