
language: swift
before_install:
   - rvm use system
   - sudo gem install cocoapods -v '1.8.0.beta.2'
osx_image: xcode11
script: xcodebuild clean build test -workspace Big\ Neon.xcworkspace -scheme "Big Neon" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.0,name=iPhone 8"
