
language: swift

before_install:
   - rvm use system
   - sudo gem install cocoapods -v '1.8.0.beta.2'

xcode_workspace: Big Neon.xcworkspace
osx_image: xcode11
xcode_scheme: BigNeonStudioTests
xcode_destination: platform=iOS Simulator,OS=11,name=iPhone 11
